# Generated by Django 6.0.2 on 2026-02-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('MANAGER', 'Manager'), ('EDITOR', 'Editor'), ('VIEWER', 'Viewer')], default='VIEWER', help_text='The role/type of this admin user.', max_length=20),
        ),
    ]
