# Generated by Django 5.2.7 on 2026-04-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_available_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='global_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
